# Generated by Django 2.0.13 on 2019-04-09 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20161113_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='desc',
            new_name='description',
        ),
    ]
