# Generated by Django 2.0.13 on 2019-04-09 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_auto_20190409_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='is_carousel',
            new_name='is_banner',
        ),
    ]
